In [1]:
%pip install semantic-link

StatementMeta(, , -1, Finished, Available)

Collecting semantic-link
  Downloading semantic_link-0.7.2-py3-none-any.whl (8.2 kB)
Collecting semantic-link-sempy==0.7.2 (from semantic-link)
  Downloading semantic_link_sempy-0.7.2-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 43.4 MB/s eta 0:00:0000:0100:01
Collecting semantic-link-functions-geopandas==0.7.2 (from semantic-link)
  Downloading semantic_link_functions_geopandas-0.7.2-py3-none-any.whl (4.0 kB)
Collecting semantic-link-functions-holidays==0.7.2 (from semantic-link)
  Downloading semantic_link_functions_holidays-0.7.2-py3-none-any.whl (4.2 kB)
Collecting semantic-link-functions-meteostat==0.7.2 (from semantic-link)
  Downloading semantic_link_functions_meteostat-0.7.2-py3-none-any.whl (4.5 kB)
Collecting semantic-link-functions-phonenumbers==0.7.2 (from semantic-link)
  Downloading semantic_link_functions_phonenumbers-0.7.2-py3-none-any.whl (4.3 kB)
Collecting semantic-link-functions-validators==0.7.2 (from semantic-link)
  Downloading semantic_link_functions_validators-0.7.2-py3-none-any.whl (4.7 kB)
Collecting geopandas (from semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading geopandas-0.14.3-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 164.3 MB/s eta 0:00:00
Collecting folium (from semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading folium-0.16.0-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 58.2 MB/s eta 0:00:00
Collecting mapclassify (from semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading mapclassify-2.6.1-py3-none-any.whl (38 kB)
Requirement already satisfied: holidays in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-functions-holidays==0.7.2->semantic-link) (0.35)
Collecting meteostat (from semantic-link-functions-meteostat==0.7.2->semantic-link)
  Downloading meteostat-1.6.7-py3-none-any.whl (31 kB)
Collecting phonenumbers (from semantic-link-functions-phonenumbers==0.7.2->semantic-link)
  Downloading phonenumbers-8.13.35-py2.py3-none-any.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 203.8 MB/s eta 0:00:00
Collecting validators (from semantic-link-functions-validators==0.7.2->semantic-link)
  Downloading validators-0.28.1-py3-none-any.whl (39 kB)
Requirement already satisfied: pythonnet>=3.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (3.0.1)
Requirement already satisfied: clr-loader>=0.2.6 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (0.2.6)
Requirement already satisfied: graphviz>=0.20.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (0.20.1)
Requirement already satisfied: pyarrow>=12.0.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (12.0.1)
Requirement already satisfied: scikit-learn>=1.3.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (1.3.0)
Requirement already satisfied: setuptools>=68.2.2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (68.2.2)
Requirement already satisfied: tqdm>=4.66.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from semantic-link-sempy==0.7.2->semantic-link) (4.66.1)
Requirement already satisfied: cffi>=1.13 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from clr-loader>=0.2.6->semantic-link-sempy==0.7.2->semantic-link) (1.16.0)
Requirement already satisfied: numpy>=1.16.6 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from pyarrow>=12.0.1->semantic-link-sempy==0.7.2->semantic-link) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from scikit-learn>=1.3.0->semantic-link-sempy==0.7.2->semantic-link) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from scikit-learn>=1.3.0->semantic-link-sempy==0.7.2->semantic-link) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from scikit-learn>=1.3.0->semantic-link-sempy==0.7.2->semantic-link) (3.2.0)
Collecting branca>=0.6.0 (from folium->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading branca-0.7.1-py3-none-any.whl (25 kB)
Requirement already satisfied: jinja2>=2.9 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from folium->semantic-link-functions-geopandas==0.7.2->semantic-link) (3.1.2)
Requirement already satisfied: requests in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from folium->semantic-link-functions-geopandas==0.7.2->semantic-link) (2.31.0)
Collecting xyzservices (from folium->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading xyzservices-2024.4.0-py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 45.3 MB/s eta 0:00:00
Collecting fiona>=1.8.21 (from geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading fiona-1.9.6-cp310-cp310-manylinux2014_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 145.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: packaging in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (23.2)
Requirement already satisfied: pandas>=1.4.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (2.0.3)
Collecting pyproj>=3.3.0 (from geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading pyproj-3.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 165.2 MB/s eta 0:00:0000:01
Collecting shapely>=1.8.0 (from geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading shapely-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 210.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from holidays->semantic-link-functions-holidays==0.7.2->semantic-link) (2.8.2)
Requirement already satisfied: networkx>=2.7 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from mapclassify->semantic-link-functions-geopandas==0.7.2->semantic-link) (3.2)
Requirement already satisfied: pytz in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from meteostat->semantic-link-functions-meteostat==0.7.2->semantic-link) (2023.3.post1)
Requirement already satisfied: pycparser in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from cffi>=1.13->clr-loader>=0.2.6->semantic-link-sempy==0.7.2->semantic-link) (2.21)
Requirement already satisfied: attrs>=19.2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (23.1.0)
Requirement already satisfied: certifi in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (2023.7.22)
Requirement already satisfied: click~=8.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (8.1.7)
Collecting click-plugins>=1.0 (from fiona>=1.8.21->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting cligj>=0.5 (from fiona>=1.8.21->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link)
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: six in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from jinja2>=2.9->folium->semantic-link-functions-geopandas==0.7.2->semantic-link) (2.1.3)
Requirement already satisfied: tzdata>=2022.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas->semantic-link-functions-geopandas==0.7.2->semantic-link) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from requests->folium->semantic-link-functions-geopandas==0.7.2->semantic-link) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from requests->folium->semantic-link-functions-geopandas==0.7.2->semantic-link) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages (from requests->folium->semantic-link-functions-geopandas==0.7.2->semantic-link) (1.26.17)
Installing collected packages: phonenumbers, xyzservices, validators, shapely, pyproj, cligj, click-plugins, fiona, branca, meteostat, mapclassify, geopandas, folium, semantic-link-sempy, semantic-link-functions-validators, semantic-link-functions-phonenumbers, semantic-link-functions-meteostat, semantic-link-functions-holidays, semantic-link-functions-geopandas, semantic-link
Successfully installed branca-0.7.1 click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.6 folium-0.16.0 geopandas-0.14.3 mapclassify-2.6.1 meteostat-1.6.7 phonenumbers-8.13.35 pyproj-3.6.1 semantic-link-0.7.2 semantic-link-functions-geopandas-0.7.2 semantic-link-functions-holidays-0.7.2 semantic-link-functions-meteostat-0.7.2 semantic-link-functions-phonenumbers-0.7.2 semantic-link-functions-validators-0.7.2 semantic-link-sempy-0.7.2 shapely-2.0.4 validators-0.28.1 xyzservices-2024.4.0

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Warning: PySpark kernel has been restarted to use updated packages.

# List Datasets

In [2]:
import sempy.fabric as fabric
dataset_list = fabric.list_datasets()

dataset_list

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 9, Finished, Available)

,Dataset Name,Dataset ID,Created Timestamp,Last Update
0,SL_Flights,b18989f3-060d-404b-8b3d-c10a4a0c4545,2024-03-07 16:43:48,NaT
1,Aviation_Lakehouse,2e92af86-60c7-4154-8c78-21d10a9d4dda,2021-02-12 23:00:58,NaT
2,SL_Flights - No Relationships,551335bf-3eb8-4113-8b5e-6bebd942fbaf,2024-03-07 16:43:48,NaT
3,USAShips,942bd9af-c68d-47f7-9e9b-8bdfd6db5b36,2024-04-19 12:25:56,NaT
4,USAShips_NoRelations,fa6afe3e-a2d4-4dbc-b391-c63be5a19423,2024-04-19 12:25:56,NaT
5,Retail Analysis,40f1c644-0b13-42db-8bf2-235eb8415186,2014-05-30 20:16:22,NaT
6,SalesOrders,35aad99f-1ad8-4985-ba20-276d941e04c4,2024-04-20 11:15:05,NaT
7,ShipmentsLakehouse,d5d34582-a4e4-47ca-94d0-8ec457f48c4b,2021-02-12 23:00:58,NaT

# Read Tables

In [3]:
dataset = "USAShips"

table_list = fabric.list_tables(dataset)

table_list

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 10, Finished, Available)

       Name Description  Hidden Data Category   Type
0      Date               False                Table
1  Shipment               False                Table
2   Product               False                Table
3    Region               False                Table

In [5]:
table_columns = fabric.list_columns(dataset)

table_columns

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 12, Finished, Available)

,Table Name,Column Name,Description,Type,Data Type,Hidden,Format String,Source,Data Category,Display Folder,...,Unique,Sort By Column,Summarize By,Is Available in MDX,Encoding Hint,State,Error Message,Alternate Of Base Column,Alternate Of Base Table,Modified Time
0,Shipment,Shipment_pk,,Data,Int64,True,0,Shipment_pk,,,...,False,None,Sum,True,Default,Ready,,None,None,2024-04-19 13:25:26
1,Shipment,Region_pk,,Data,Int64,True,0,Region_pk,,,...,False,None,None,True,Default,Ready,,None,None,2024-04-19 13:26:14
2,Shipment,Product_pk,,Data,Int64,True,0,Product_pk,,,...,False,None,None,True,Default,Ready,,None,None,2024-04-19 13:26:16
3,Shipment,Quantity,,Data,Int64,False,0,Quantity,,,...,False,None,Sum,True,Default,Ready,,None,None,2024-04-19 13:24:49
4,Shipment,Date,,Data,DateTime,False,Long Date,Date,,,...,False,None,None,True,Default,Ready,,None,None,2024-04-19 13:24:49

In [6]:

shipment_df = fabric.read_table(dataset, 'Shipment')

shipment_df

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 13, Finished, Available)

     Shipment_pk  Region_pk  Product_pk  Quantity       Date
0             20         18         197         9 2022-06-24
1             23          7          39         9 2022-07-04
2             43         46          31         9 2022-10-29
3             52         49          20         9 2022-12-23
4             61          5          63         9 2022-09-22
..           ...        ...         ...       ...        ...
995          925         20          70         2 2024-03-01
996          938         42         167         2 2023-07-16
997          945         27          50         2 2022-08-12
998          946         43         149         2 2022-05-04
999          972         17          10         2 2023-01-02

[1000 rows x 5 columns]

In [7]:
shipment_df.to_lakehouse_table(name="shipment",mode="overwrite")

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 14, Finished, Available)

# Relationships

In [8]:
from sempy.relationships import plot_relationship_metadata
from sempy.relationships import find_relationships
from sempy.fabric import list_relationship_violations

relationships = fabric.list_relationships(dataset)
relationships

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 15, Finished, Available)

,Multiplicity,From Table,From Column,To Table,To Column,Active,Cross Filtering Behavior,Security Filtering Behavior,Join On Date Behavior,Rely On Referential Integrity,State,Modified Time,Relationship Name
0,m:1,Shipment,Region_pk,Region,Region_pk,True,OneDirection,OneDirection,DateAndTime,False,Ready,2024-04-19 13:51:37,1d637e30-b1f1-46e5-941e-5b514bb4a513
1,m:1,Shipment,Product_pk,Product,Product_pk,True,OneDirection,OneDirection,DateAndTime,False,Ready,2024-04-19 13:51:37,7198803d-e9ec-4ad1-80ee-f4d60a5709cc
2,m:1,Shipment,Date,Date,Date,True,OneDirection,OneDirection,DateAndTime,False,Ready,2024-04-19 13:51:37,ac17b76b-7186-4dde-b1bf-6eb2154e9258

In [9]:
plot_relationship_metadata(relationships)

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 16, Finished, Available)

### Relationships Violations

In [10]:
tables = {table: fabric.read_table(dataset, table) for table in fabric.list_tables(dataset)['Name']}

tables.keys()

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 17, Finished, Available)

dict_keys(['Date', 'Shipment', 'Product', 'Region'])

In [11]:
list_relationship_violations(tables, fabric.list_relationships(dataset))

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 18, Finished, Available)

,Multiplicity,From Table,From Column,To Table,To Column,Type,Message
0,m:1,Shipment,Region_pk,Region,Region_pk,partial join,6 out of 56 values in Shipment[Region_pk] not ...
1,m:1,Shipment,Product_pk,Product,Product_pk,partial join,4 out of 203 values in Shipment[Product_pk] no...

In [13]:
shipment_df = fabric.read_table(dataset, 'Shipment')
product_df = fabric.read_table(dataset, 'Product')

join_df = shipment_df.join(product_df, shipment_df.product_pk == product_df.product_pk, "left_outer")

# Filtrar onde não há correspondência
no_match_df = join_df.filter(product_df.product_pk.isNull())

# Mostrar resultados
no_match_df.show()

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 20, Finished, Available)

AttributeError: 'FabricDataFrame' object has no attribute 'product_pk'

### Find New Relationships

In [14]:
dataset_no_relationship = "USAShips_NoRelations"
actual_relationships = fabric.list_relationships(dataset_no_relationship)
plot_relationship_metadata(actual_relationships)

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 30, Finished, Available)

In [15]:
tables = {table: fabric.read_table(dataset_no_relationship, table) for table in fabric.list_tables(dataset_no_relationship)['Name']}

tables.keys()

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 31, Finished, Available)

dict_keys(['Date', 'Shipment', 'Product', 'Region'])

In [16]:

additional_relationships = find_relationships(
    tables,
    exclude=actual_relationships,
    name_similarity_threshold=0.7, # Default=0.8
    coverage_threshold=0.7 # Default=1 
)

additional_relationships

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 32, Finished, Available)

,Multiplicity,From Table,From Column,To Table,To Column,Coverage From,Coverage To,Null Count From,Null Count To,Unique Count From,Unique Count To,Row Count From,Row Count To
0,m:1,Shipment,Date,Date,Date,1.000000,0.358658,0,0,524,1461,1000,1461
1,m:1,Shipment,Product_pk,Product,Product_pk,0.980296,0.995000,0,0,203,200,1000,200
2,m:1,Shipment,Region_pk,Region,Region_pk,0.892857,0.943396,0,0,56,53,1000,53

# Dependencies

In [17]:
from sempy.dependencies import plot_dependency_metadata

region = fabric.read_table(dataset, "Region")
region

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 33, Finished, Available)

    Region_pk Country           State  Zip_code                    City
0           1     USA        Missouri     52775            New Tinaview
1           2     USA       Wisconsin     93595               Jonesberg
2           3     USA        Nebraska     88077             North Megan
3           4     USA         Arizona     82455             Masseyhaven
4           5     USA        Kentucky       650               Aimeebury
5           6     USA  North Carolina     80703           Lake Brittany
6           7     USA        New York     65195              Rileymouth
7           8     USA         Montana     44165              Kellerstad
8           9     USA        Maryland     32470          West Chloefort
9          10     USA      New Mexico     96220               Meganbury
10         11     USA       Minnesota     43126         Lake Josephbury
11         12     USA    Pennsylvania     92728              Lauramouth
12         13     USA         Indiana      8756            Cabreraville
13         14     USA  North Carolina     25544              Port Heidi
14         15     USA         Florida     74885         Port Audreyside
15         16     USA           Maine     29560      North Davidborough
16         17     USA         Florida     31776  South Christopherville
17         18     USA       Wisconsin     19178         New Andrewburgh
18         19     USA     Connecticut     71671          South Jasonton
19         20     USA  South Carolina     59217         New Ronaldville
20         21     USA        Kentucky     12456                Chadland
21         22     USA            Ohio     11045            Michaelburgh
22         23     USA        Virginia     42451         New Tannerville
23         24     USA    Rhode Island     67077            Gonzalezstad
24         25     USA         Georgia     64632             Masseyshire
25         26     USA        Maryland     14795              Lake Emily
26         27     USA     Connecticut     40012         Port Ericaburgh
27         28     USA      Washington     72756             Alyssaville
28         29     USA      California     38654                Wadetown
29         30     USA            Utah     93111          Maldonadoshire
30         31     USA        Michigan     16860             Deborahfurt
31         32     USA      New Mexico     72255                Erictown
32         33     USA        Oklahoma     44115             Harmonmouth
33         34     USA     Connecticut     71317            New Juanbury
34         35     USA       Minnesota     27135                Bellport
35         36     USA          Nevada     79561            Brittanyberg
36         37     USA   Massachusetts     72227             Paulchester
37         38     USA  South Carolina     77521       North Brookemouth
38         39     USA    South Dakota     38204            East Jeffrey
39         40     USA         Indiana     58826               Grayshire
40         41     USA        Oklahoma     12511            Johnsonshire
41         42     USA      New Mexico     78657               Bartonton
42         43     USA   New Hampshire     50950             South Caleb
43         44     USA    North Dakota     42056           South Allison
44         45     USA        Kentucky     75952            Odonnelltown
45         46     USA        Arkansas     32234         South Markmouth
46         47     USA        Oklahoma     38555   Port Mackenziechester
47         48     USA         Alabama     24601              New Yvonne
48         49     USA        Colorado     25324        Port Jessicatown
49         50     USA      Washington     24976          Herringchester
50         51     USA      Washington     24976          Herringchester
51         52     USA         Montana     44165          West Chloefort
52         53     USA         Alabama     24601              New Yvonne
53         54     USA        Missouri     24601            New Tinaview
54         55     USA         Indiana     24976               Grayshire

### Find Dependencies

In [18]:
dependencies = region.find_dependencies()
dependencies

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 34, Finished, Available)

,Determinant,Dependent,Conditional Entropy,Determinant Unique Count,Dependent Unique Count,Determinant Null Count,Dependent Null Count
0,Region_pk,City,0.0,55,50,0,0
1,Region_pk,Zip_code,0.0,55,50,0,0
2,Region_pk,State,0.0,55,34,0,0
3,Zip_code,Country,0.0,50,1,0,0
4,City,Country,0.0,50,1,0,0
5,State,Country,0.0,34,1,0,0

In [19]:
plot_dependency_metadata(dependencies)

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 35, Finished, Available)

### Find Dependencies Violations

In [20]:
region.plot_dependency_violations('Zip_code', 'State')

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 36, Finished, Available)

In [21]:
region.plot_dependency_violations('Zip_code', 'City')

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 37, Finished, Available)

In [22]:
region.list_dependency_violations('Zip_code', 'City')

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 38, Finished, Available)

   Zip_code            City  count
0     24601      New Yvonne      2
1     24601    New Tinaview      1
2     24976  Herringchester      2
3     24976       Grayshire      1
4     44165      Kellerstad      1
5     44165  West Chloefort      1

# Measures

### List measures

In [23]:
dataset_flights = "SL_Flights"

fabric.list_measures(dataset_flights)

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 39, Finished, Available)

,Table Name,Measure Name,Measure Expression,Measure Data Type,Measure Hidden,Measure Display Folder,Measure Description,Format String,Data Category,Detail Rows Definition,Format String Definition
0,Delays,# Delays,COUNTROWS(Delays),Int64,False,,,"#,0",,None,None
1,Delays,# Airlines,DISTINCTCOUNT(Delays[IATAAirline]),Int64,False,,,0,,None,None
2,Delays,# Airports (Destination),DISTINCTCOUNT(Delays[IATADestination]),Int64,False,,,"#,0",,None,None
3,Delays,# Airports (Origin),DISTINCTCOUNT(Delays[IATAOrigin]),Int64,False,,,"#,0",,None,None
4,Delays,Delay (min),SUM('Delay Reasons'[Duration]),Int64,False,,,"#,0",,None,None
5,Delays,Delay (h),"DIVIDE([Delay (min)], 60)",Double,False,,,"#,0",,None,None

### Evaluate Measure

In [24]:
#fabric.evaluate_measure(dataset_flights, measure="# Delays")

# Delays by Airline and Airline Country
fabric.evaluate_measure(dataset_flights, measure="# Delays", groupby_columns=["Airline[Airline]", "Airline[Country (Airline)]"])

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 40, Finished, Available)

                        Airline Country (Airline)  # Delays
0               Alaska Airlines            ALASKA     71706
1             American Airlines     United States    486615
2       American Eagle Airlines     United States    400219
3   Atlantic Southeast Airlines     United States    196381
4               Delta Air Lines     United States    203594
5             Frontier Airlines     United States     61263
6             Hawaiian Airlines     United States      9534
7               JetBlue Airways     United States    108091
8                       SkyWest     United States    347187
9            Southwest Airlines     United States    821058
10              United Airlines     United States    379932
11                   US Airways     United States    212976

In [25]:
# Delays by Airline and Origin Airport only from Alaska

fabric.evaluate_measure(dataset_flights, measure="# Delays", groupby_columns=["Airline[Airline]", "Airport (Origin)[Airport (Origin)]"], filters={"Airport (Origin)[State (Origin)]": ["Alaska"]})

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 41, Finished, Available)

              Airline                             Airport (Origin)  # Delays
0     Alaska Airlines                                 Adak Airport        53
1     Alaska Airlines                               Bethel Airport       532
2     Alaska Airlines                            Deadhorse Airport       316
3     Alaska Airlines                           Dillingham Airport        69
4     Alaska Airlines              Fairbanks International Airport      1638
5     Alaska Airlines                 Juneau International Airport      2461
6     Alaska Airlines              Ketchikan International Airport      1429
7     Alaska Airlines                          King Salmon Airport        69
8     Alaska Airlines                               Kodiak Airport       329
9     Alaska Airlines              Merle K (Mudhole) Smith Airport       477
10    Alaska Airlines                                 Nome Airport       434
11    Alaska Airlines           Petersburg James A Johnson Airport       470
12    Alaska Airlines                  Ralph Wien Memorial Airport       472
13    Alaska Airlines                Sitka Rocky Gutierrez Airport       573
14    Alaska Airlines  Ted Stevens Anchorage International Airport      5599
15    Alaska Airlines      Wiley Post Will Rogers Memorial Airport       446
16    Alaska Airlines                             Wrangell Airport       355
17    Alaska Airlines                              Yakutat Airport       410
18  American Airlines  Ted Stevens Anchorage International Airport       159
19    Delta Air Lines              Fairbanks International Airport         5
20    Delta Air Lines  Ted Stevens Anchorage International Airport       143
21  Frontier Airlines  Ted Stevens Anchorage International Airport       112
22    United Airlines  Ted Stevens Anchorage International Airport       178
23         US Airways  Ted Stevens Anchorage International Airport       318

In [26]:
%load_ext sempy

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 42, Finished, Available)

In [27]:
%%dax "SL_Flights"

SELECT * FROM $System.DISCOVER_CALC_DEPENDENCY WHERE OBJECT_TYPE = 'ACTIVE_RELATIONSHIP'

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 43, Finished, Available)

,DATABASE_NAME,OBJECT_TYPE,TABLE,OBJECT,EXPRESSION,REFERENCED_OBJECT_TYPE,REFERENCED_TABLE,REFERENCED_OBJECT,REFERENCED_EXPRESSION,QUERY
0,SL_Flights,ACTIVE_RELATIONSHIP,Delays,51f7df70-195f-4f5c-b901-78cde017d9d8,<NA>,COLUMN,Airport (Origin),IATA (Origin),<NA>,<NA>
1,SL_Flights,ACTIVE_RELATIONSHIP,Delays,51f7df70-195f-4f5c-b901-78cde017d9d8,<NA>,COLUMN,Delays,IATAOrigin,<NA>,<NA>
2,SL_Flights,ACTIVE_RELATIONSHIP,Delays,48f37d31-9017-48ff-b467-e7046cda78af,<NA>,COLUMN,Airport (Destination),IATA (Destination),<NA>,<NA>
3,SL_Flights,ACTIVE_RELATIONSHIP,Delays,48f37d31-9017-48ff-b467-e7046cda78af,<NA>,COLUMN,Delays,IATADestination,<NA>,<NA>
4,SL_Flights,ACTIVE_RELATIONSHIP,Delays,68790b95-f5ea-4041-a4a0-f8c52a50004b,<NA>,COLUMN,Delays,Date,<NA>,<NA>
5,SL_Flights,ACTIVE_RELATIONSHIP,Delays,68790b95-f5ea-4041-a4a0-f8c52a50004b,<NA>,COLUMN,Calendar,Date,<NA>,<NA>
6,SL_Flights,ACTIVE_RELATIONSHIP,Delays,2eaec8c5-9f3a-4802-9c2b-7d883a0fa239,<NA>,COLUMN,Delays,Time (Arrival),<NA>,<NA>
7,SL_Flights,ACTIVE_RELATIONSHIP,Delays,2eaec8c5-9f3a-4802-9c2b-7d883a0fa239,<NA>,COLUMN,Time (Arrival),Minute,<NA>,<NA>
8,SL_Flights,ACTIVE_RELATIONSHIP,Delays,99c016b4-5274-47ea-9d60-169178f29006,<NA>,COLUMN,Delays,Time (Departure),<NA>,<NA>
9,SL_Flights,ACTIVE_RELATIONSHIP,Delays,99c016b4-5274-47ea-9d60-169178f29006,<NA>,COLUMN,Time (Departure),Minute,<NA>,<NA>
10,SL_Flights,ACTIVE_RELATIONSHIP,Delays,bea6023e-01de-491b-b2f1-1c5239611e24,<NA>,COLUMN,Delays,IATAAirline,<NA>,<NA>
11,SL_Flights,ACTIVE_RELATIONSHIP,Delays,bea6023e-01de-491b-b2f1-1c5239611e24,<NA>,COLUMN,Airline,IATA (Airline),<NA>,<NA>
12,SL_Flights,ACTIVE_RELATIONSHIP,Latitude,a6348359-5fdb-4e04-b88e-bbc986231a34,<NA>,CALC_COLUMN,Latitude,AirportLocation,<NA>,<NA>
13,SL_Flights,ACTIVE_RELATIONSHIP,Latitude,a6348359-5fdb-4e04-b88e-bbc986231a34,<NA>,CALC_COLUMN,AirportLocation,AirportLocation,<NA>,<NA>
14,SL_Flights,ACTIVE_RELATIONSHIP,Longitude,071e3e47-cac0-4002-8bef-c137ec5c8a23,<NA>,CALC_COLUMN,Longitude,AirportLocation,<NA>,<NA>
15,SL_Flights,ACTIVE_RELATIONSHIP,Longitude,071e3e47-cac0-4002-8bef-c137ec5c8a23,<NA>,CALC_COLUMN,AirportLocation,AirportLocation,<NA>,<NA>
16,SL_Flights,ACTIVE_RELATIONSHIP,Delay Reasons,4f74c129-693f-491c-a07e-ac109ffb6ee2,<NA>,COLUMN,Delay Reasons,DelayID,<NA>,<NA>
17,SL_Flights,ACTIVE_RELATIONSHIP,Delay Reasons,4f74c129-693f-491c-a07e-ac109ffb6ee2,<NA>,COLUMN,Delays,DelayID,<NA>,<NA>

In [28]:
spark.conf.set("spark.sql.catalog.pbi", "com.microsoft.azure.synapse.ml.powerbi.PowerBICatalog")

StatementMeta(, 475c8863-cbfc-4700-bab8-39f6d66769e3, 44, Finished, Available)

In [ ]:
%%sql 

SELECT
    
    `Airport (Origin)[Airport (Origin)]` AS Origin,
    SUM(`# Airlines`) as TotalAirlines

FROM pbi.`SL_Flights`.`_Metrics`
GROUP BY `Airport (Origin)[Airport (Origin)]`